# Names for lists of structures
CIRCULAR_DOUBLY_LINKED_LISTS = 'cyclics'
LINEAR_DOUBLY_LINKED_LISTS = 'linears'
TREES = 'trees'
ARRAYS_OF_POINTERS = 'arrays'
LINKED_LISTS = 'lists'
ARRAYS_OF_STRINGS = 'arrays_strings'
DERIVED_STRUCTURES = 'derived'
CHILDREN_STRUCTURES = 'children'

# Filenames
#   Generic
ELF_MEMORY_DUMP_FILE = 'dump.elf'
KERNEL_FILE = 'extracted_kernel.elf'
#   Extracted features
PREFIX = 'extracted_'
EXTENSION = '.lzma'
DOUBLY_LINKED_LISTS_FILE = PREFIX + 'doubly_linked_lists' + EXTENSION
BITMAP_FILE = PREFIX + 'btm' + EXTENSION
FUNCTIONS_FILE = PREFIX + 'functions' + EXTENSION
OFFSETS_TO_VIRTUALS_FILE = PREFIX + 'o2v' + EXTENSION
VIRTUALS_TO_OFFSETS_FILE = PREFIX + 'v2o' + EXTENSION
POINTERS_FILE = PREFIX + 'ptrs' + EXTENSION
INVERSE_POINTERS_FILE = PREFIX + 'rptrs' + EXTENSION
STRINGS_FILE = PREFIX + 'strs' + EXTENSION
EXTERNAL_REFERENCES_FILE = PREFIX + 'xrefs' + EXTENSION
TREES_FILE = PREFIX + 'trees' + EXTENSION
RESULTS_FILE = 'results' + EXTENSION